import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/theme/globals.css";
import SessionProvider from "./SessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import Login from "./Login";
import Home from "./page";
import StoreProvider from "./StoreProvider";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import DesignProvider from "./ThemeProvider";
import { ThemeContextProvider } from "@/theme/ThemeContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by tanmoy barash",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let session = await getServerSession(authOptions);
  console.log("s: ", session);

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeContextProvider>
            <DesignProvider>
              <SessionProvider session={session}>
                <StoreProvider>{!session ? <Login /> : <Home />}</StoreProvider>
              </SessionProvider>
            </DesignProvider>
          </ThemeContextProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
